stages:
  - lint
  - build
  - test
  - deploy
  - quality
  - release

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_MERGE_REQUEST_IID

#### Templates ####
.TEMPLATE:PHP:CLI:
  image: php:7.4-cli
  stage: lint
  script:
    - find . -name \*.php -exec php -l "{}" \;
  dependencies: [ ]

.TEMPLATE:PHP:phpstan:
  image:
    name: phpstan/phpstan
    entrypoint: [ "" ]
  stage: lint
  script:
    - phpstan analyse src/ | tee phpstan.txt
  dependencies: [ ]

.TEMPLATE:MD:markdownlint:
  stage: lint
  image: node:latest
  before_script:
    - npm install -g markdownlint-cli
  script:
    - markdownlint .
  dependencies: [ ]

.TEMPLATE:BASH:shellcheck:
  image: koalaman/shellcheck-alpine
  stage: lint
  script:
    - shellcheck cam/templates/*
  dependencies: [ ]

.TEMPLATE:PHP:noverify:
  image: golang:alpine
  stage: lint
  before_script:
    - apk add --no-cache git
    - go get -u github.com/VKCOM/noverify
  script:
    - noverify -cache-dir=/tmp/cache/noverify src/ | tee noverify.txt

.TEMPLATE:DOCS:mkdocs:
  stage: deploy
  image: python:3.9-alpine
  before_script:
    - apk add --no-cache --virtual .build gcc musl-dev
    - pip install mkdocs-material
    - pip install mkdocs-minify-plugin
  dependencies: [ ]

.TEMPLATE:DOCKER:build:
  image: docker:stable
  stage: build
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
  services:
    - name: docker:stable-dind
      command: [ "--experimental" ]
  before_script:
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v$BUILDX_VERSION/buildx-v$BUILDX_VERSION.linux-amd64
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - apk add --no-cache jq
    - export ACUPARSE_VERSION=$(cat .version | jq -r '.VERSION')
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container --name custom --platform=$BUILDX_PLATFORM
    - docker buildx inspect --bootstrap
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
  script:
    - >
      if [ "$TAGGED_RELEASE" = "true" ]; then
        docker buildx build \
        --build-arg BUILD_DATE=$DATE \
        --build-arg VCS_REF=$CI_COMMIT_SHA \
        --build-arg BUILD_VERSION=$ACUPARSE_VERSION \
        --build-arg BUILD_BRANCH=stable \
        --tag $CI_REGISTRY_IMAGE:$ACUPARSE_VERSION \
        --tag $CI_REGISTRY_IMAGE:latest \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$ACUPARSE_VERSION \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest \
        --tag $DOCKER_REGISTRY_TAG:$ACUPARSE_VERSION \
        --tag $DOCKER_REGISTRY_TAG:latest \
        --platform $BUILDX_PLATFORM \
        --push \
        .
      else
        docker buildx build \
        --build-arg BUILD_DATE=$DATE \
        --build-arg VCS_REF=$CI_COMMIT_SHA \
        --build-arg BUILD_VERSION=$ACUPARSE_VERSION \
        --build-arg BUILD_BRANCH=$CI_COMMIT_REF_SLUG \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$ACUPARSE_VERSION \
        --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest \
        --platform $BUILDX_PLATFORM_DEV \
        --push \
        .
      fi
  dependencies: [ ]

#### END: Templates ####

#### PHP ####

#### PHP CLI ####
PHP:CLI:
  extends: .TEMPLATE:PHP:CLI
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'

DEV:PHP:CLI:
  extends: .TEMPLATE:PHP:CLI
  image: php:8.0-rc-cli
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never
  allow_failure: true

#### phpstan ####

DEV:PHP:phpstan:
  extends: .TEMPLATE:PHP:phpstan
  script:
    - phpstan analyse --level max src/ | tee phpstan.txt
  artifacts:
    when: on_failure
    paths:
      - phpstan.txt
    expire_in: 2 weeks
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never

#### noverify ####

DEV:PHP:noverify:
  extends: .TEMPLATE:PHP:noverify
  artifacts:
    when: on_failure
    paths:
      - noverify.txt
    expire_in: 2 weeks
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never

#### END: PHP ####

#### Markdown ####
MD:markdownlint:
  extends: .TEMPLATE:MD:markdownlint
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'

DEV:MD:markdownlint:
  extends: .TEMPLATE:MD:markdownlint
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never
  allow_failure: true

#### END: Markdown ####

#### Bash ####
BASH:shellcheck:
  extends: .TEMPLATE:BASH:shellcheck
  before_script:
    - export SHELLCHECK_OPTS="-e SC2034 -e SC2059 -e SC2086"
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'

DEV:BASH:shellcheck:
  extends: .TEMPLATE:BASH:shellcheck
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never
  allow_failure: true

#### END: Bash ####

#### Build and Release a Docker Container ####

DOCKER:build:RELEASE:
  extends: .TEMPLATE:DOCKER:build
  variables:
    TAGGED_RELEASE: 'true'
  rules:
    - if: $CI_COMMIT_TAG

DEV:DOCKER:build:
  extends: .TEMPLATE:DOCKER:build
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'

#### END: Docker Image ####

#### Test Installer and Container ####
INSTALLER:
  stage: test
  trigger:
    project: acuparse/installer
    branch: dev
    strategy: depend
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
      when: never

#### END: Test Installer ####

#### Publish Project Documentation ####
pages:
  extends: .TEMPLATE:DOCS:mkdocs
  script:
    - mkdocs build
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'
  artifacts:
    paths:
      - public

DEV:DOCS:mkdocs:
  extends: .TEMPLATE:DOCS:mkdocs
  script:
    - mkdocs build --site-dir test
  rules:
    - if: '$CI_COMMIT_BRANCH != "stable"'
    - if: $CI_COMMIT_TAG
      when: never
  allow_failure: true
  artifacts:
    paths:
      - test

#### END: Project Documentation ####

#### Update Release ####
RELEASE:tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    - if: '$CI_COMMIT_BRANCH == "stable"'
      when: manual
  before_script:
    - apk add curl jq --no-cache
    - export VERSION=$(cat .version | jq -r '.VERSION')
  script:
    - release-cli create --name "Version $VERSION" --description "Release Version $VERSION" --tag-name "v$VERSION" --ref "$CI_COMMIT_SHA"
  dependencies: [ ]

#### Update Release ####
TEST:RELEASE:tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  before_script:
    - apk add curl jq --no-cache
    - export VERSION=$(cat .version | jq -r '.VERSION')
  script:
    - echo release-cli create --name "Version $VERSION" --description "Release Version $VERSION" --tag-name "v$VERSION" --ref "$CI_COMMIT_SHA"
  dependencies: [ ]

RELEASE:RMS:version:
  image: alpine
  stage: release
  before_script:
    - apk add curl jq --no-cache
    - export VERSION=$(cat .version | jq -r '.VERSION')
  script:
    - >
      curl -H "Authorization: Bearer $RMS_TOKEN" -X POST -d "version=$VERSION" "$RMS_HOST/releases" | jq
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9](?:\.[0-9]){2,3}.*/
  dependencies: [ ]

#### End Release ####

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
